"""
Configuration: environment variables are the source of truth, optionally
hydrated from a .env file (real env always wins over .env).

The interactive menu can persist values back to .env (chmod 600). .env is
gitignored and must never be committed. No third-party deps — a small parser
handles .env so we don't pull in python-dotenv.
"""
import os
from dataclasses import dataclass
from pathlib import Path

from . import naming

# field name, env var, is_secret, default
SPEC = [
    ("site_jira",            "SITE_JIRA",                        False, ""),
    ("site_confluence",      "SITE_CONFLUENCE",                  False, ""),
    ("atl_email",            "ATL_EMAIL",                        False, ""),
    ("atl_token",            "ATL_TOKEN",                        True,  ""),
    ("jira_cookies",         "JIRA_COOKIES",                     True,  ""),
    ("archive_password",     "ARCHIVE_PASSWORD",                 True,  ""),
    ("product_name_template","PRODUCT_NAME_TEMPLATE",            False, naming.DEFAULT_PRODUCT_TEMPLATE),
    ("archive_name_template","ARCHIVE_NAME_TEMPLATE",            False, naming.DEFAULT_ARCHIVE_TEMPLATE),
    ("archive_compression",  "ARCHIVE_COMPRESSION",              False, "5"),
    ("storage_provider",     "STORAGE_PROVIDER",                 False, "gcs"),
    ("storage_dest",         "STORAGE_DEST",                     False, ""),
    ("gcp_credentials",      "GOOGLE_APPLICATION_CREDENTIALS",   False, ""),
    ("s3_endpoint_url",      "S3_ENDPOINT_URL",                  False, ""),
    ("aws_access_key_id",    "AWS_ACCESS_KEY_ID",                True,  ""),
    ("aws_secret_access_key","AWS_SECRET_ACCESS_KEY",            True,  ""),
    ("aws_default_region",   "AWS_DEFAULT_REGION",               False, ""),
    ("azure_conn",           "AZURE_STORAGE_CONNECTION_STRING",  True,  ""),
    ("notify_channels",      "NOTIFY_CHANNELS",                  False, "google-chat"),
    ("notify_webhook_url",   "NOTIFY_WEBHOOK_URL",               True,  ""),
    ("smtp_host",            "SMTP_HOST",                        False, ""),
    ("smtp_port",            "SMTP_PORT",                        False, "587"),
    ("smtp_starttls",        "SMTP_STARTTLS",                    False, "true"),
    ("smtp_user",            "SMTP_USER",                        False, ""),
    ("smtp_password",        "SMTP_PASSWORD",                    True,  ""),
    ("smtp_from",            "SMTP_FROM",                        False, ""),
    ("smtp_to",              "SMTP_TO",                          False, ""),
]
_ENV = {name: env for name, env, _, _ in SPEC}
_SECRET = {name for name, _, secret, _ in SPEC if secret}


@dataclass
class Config:
    site_jira: str = ""
    site_confluence: str = ""
    atl_email: str = ""
    atl_token: str = ""
    jira_cookies: str = ""
    archive_password: str = ""
    product_name_template: str = naming.DEFAULT_PRODUCT_TEMPLATE
    archive_name_template: str = naming.DEFAULT_ARCHIVE_TEMPLATE
    archive_compression: str = "5"
    storage_provider: str = "gcs"
    storage_dest: str = ""
    gcp_credentials: str = ""
    s3_endpoint_url: str = ""
    aws_access_key_id: str = ""
    aws_secret_access_key: str = ""
    aws_default_region: str = ""
    azure_conn: str = ""
    notify_channels: str = "google-chat"
    notify_webhook_url: str = ""
    smtp_host: str = ""
    smtp_port: str = "587"
    smtp_starttls: str = "true"
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_from: str = ""
    smtp_to: str = ""


def parse_env_file(path: Path) -> dict[str, str]:
    """Minimal KEY=VALUE .env parser. Ignores blanks/comments, strips quotes."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        out[key] = val
    return out


def load(env_file: Path | None = None) -> Config:
    """Load .env (if present) into the process env without clobbering real env,
    then build a Config from the environment."""
    path = env_file or Path(".env")
    for key, val in parse_env_file(path).items():
        os.environ.setdefault(key, val)            # real env wins over .env
    values = {name: os.environ.get(env, default) for name, env, _, default in SPEC}
    return Config(**values)


def save_env(cfg: Config, path: Path | None = None) -> Path:
    """Write the config to a .env file (chmod 600). Skips empty values."""
    path = path or Path(".env")
    lines = ["# Generated by main.py Configure. Gitignored — never commit.\n"]
    for name, env, _, _ in SPEC:
        val = getattr(cfg, name)
        if val:
            lines.append(f"{env}={val}\n")
    path.write_text("".join(lines), encoding="utf-8")
    try:
        path.chmod(0o600)                          # best-effort; no-op semantics on Windows
    except OSError:
        pass
    return path


def mask(value: str) -> str:
    if not value:
        return "(not set)"
    if len(value) <= 6:
        return "***"
    return f"{value[:3]}...{value[-2:]} ({len(value)} chars)"


def display_rows(cfg: Config) -> list[tuple[str, str]]:
    """Key/value rows for showing config — secrets masked."""
    rows = []
    for name, env, secret, _ in SPEC:
        val = getattr(cfg, name)
        shown = mask(val) if secret else (val or "(not set)")
        rows.append((env, shown))
    return rows
