"""
Generate a Jenkins Script Console (Groovy) script from the local config that
creates every credential the Jenkinsfile expects (with the exact IDs) plus the
pipeline job — so a first-time Jenkins setup is one paste instead of a dozen
manual forms.

Run it in Jenkins: Manage Jenkins -> Script Console -> paste -> Run.

The generated file embeds REAL secrets (base64-encoded, not encrypted). It is
gitignored; delete it after importing.
"""
import base64
from pathlib import Path

from . import config

DEFAULT_REPO = "https://github.com/davidmalko87/jira-confluence-full-instance-backup.git"
DEFAULT_JOB = "atlassian-full-backup"
DEFAULT_BRANCH = "*/master"
_WEBHOOK_HINTS = ("chat", "slack", "discord", "teams", "webhook")


def _b64(s: str) -> str:
    return base64.b64encode((s or "").encode("utf-8")).decode("ascii")


def _text_cred(cid: str, value: str) -> str:
    return (f'upsert(new StringCredentialsImpl(CredentialsScope.GLOBAL, "{cid}", '
            f'"{cid}", Secret.fromString(b64d(\'{_b64(value)}\'))))')


def _file_cred(cid: str, filename: str, raw: bytes) -> str:
    b64 = base64.b64encode(raw).decode("ascii")
    return (f'upsert(new FileCredentialsImpl(CredentialsScope.GLOBAL, "{cid}", '
            f'"{cid}", "{filename}", SecretBytes.fromBytes(\'{b64}\'.decodeBase64())))')


_TEMPLATE = """\
// Generated by jira-confluence-full-instance-backup — Jenkins setup.
// Paste into: Manage Jenkins -> Script Console -> Run.
// CONTAINS SECRETS (base64, not encrypted) — delete this file after running.
import jenkins.model.Jenkins
import com.cloudbees.plugins.credentials.CredentialsScope
import com.cloudbees.plugins.credentials.SystemCredentialsProvider
import com.cloudbees.plugins.credentials.SecretBytes
import com.cloudbees.plugins.credentials.domains.Domain
import org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl
import org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl
import hudson.util.Secret
import hudson.slaves.EnvironmentVariablesNodeProperty
import org.jenkinsci.plugins.workflow.job.WorkflowJob
import org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition
import hudson.plugins.git.GitSCM
import hudson.plugins.git.BranchSpec

def jenkins = Jenkins.get()
def store = SystemCredentialsProvider.getInstance().getStore()
def domain = Domain.global()
def b64d = { String s -> new String(s.decodeBase64(), "UTF-8") }
def upsert = { cred ->
    def existing = store.getCredentials(domain).find { it.id == cred.id }
    if (existing != null) { store.updateCredentials(domain, existing, cred) }
    else { store.addCredentials(domain, cred) }
    println("  credential: " + cred.id)
}

println("Creating/updating credentials...")
%%CRED_BLOCK%%

println("Setting global (non-secret) configuration env vars...")
def gnp = jenkins.getGlobalNodeProperties()
def envProp = gnp.getAll(EnvironmentVariablesNodeProperty).isEmpty() ? null \
              : gnp.getAll(EnvironmentVariablesNodeProperty).get(0)
if (envProp == null) { envProp = new EnvironmentVariablesNodeProperty(); gnp.add(envProp) }
def ev = envProp.getEnvVars()
%%ENV_BLOCK%%
jenkins.save()

println("Creating/updating pipeline job...")
def jobName = "%%JOB%%"
def job = jenkins.getItemByFullName(jobName, WorkflowJob)
if (job == null) { job = jenkins.createProject(WorkflowJob, jobName) }
def scm = new GitSCM(
    GitSCM.createRepoList("%%REPO%%", null),
    [new BranchSpec("%%BRANCH%%")],
    null, null, []
)
def flow = new CpsScmFlowDefinition(scm, "Jenkinsfile")
flow.setLightweight(true)
job.setDefinition(flow)
job.save()
println("  job: " + jobName)

println("")
println("Done. Review the credentials and the '" + jobName + "' job, then DELETE")
println("the generated jenkins-setup.groovy file — it contains secrets.")
"""


def build(cfg: config.Config, *, repo: str = DEFAULT_REPO, job: str = DEFAULT_JOB,
          branch: str = DEFAULT_BRANCH) -> tuple[str, list[str]]:
    """Return (groovy_script, summary). Summary lists what gets created (no secrets)."""
    creds: list[str] = []
    summary: list[str] = []

    def text(cid: str, value: str) -> None:
        creds.append(_text_cred(cid, value))
        summary.append(f"{cid} (secret text)")

    if cfg.jira_cookies:
        text("jira-cookies", cfg.jira_cookies)
    if cfg.atl_email:
        text("atlassian-email", cfg.atl_email)
    if cfg.atl_token:
        text("atlassian-api-token", cfg.atl_token)
    # Always create archive-password (the Archive stage binds it); empty = unencrypted.
    text("archive-password", cfg.archive_password)

    # STORAGE_PROVIDER may be a comma list — create credentials for each backend.
    for prov in [p.strip() for p in (cfg.storage_provider or "").split(",") if p.strip()]:
        if prov == "gcs":
            key = Path(cfg.gcp_credentials or "")
            if key.is_file():
                creds.append(_file_cred("gcp-backup-sa-key", key.name or "sa-key.json",
                                        key.read_bytes()))
                summary.append("gcp-backup-sa-key (secret file)")
            else:
                summary.append("!! gcp-backup-sa-key SKIPPED — key file not found at "
                               f"'{cfg.gcp_credentials or '(unset)'}'")
        elif prov == "s3":
            if cfg.aws_access_key_id:
                text("aws-access-key-id", cfg.aws_access_key_id)
            if cfg.aws_secret_access_key:
                text("aws-secret-access-key", cfg.aws_secret_access_key)
        elif prov == "azure":
            if cfg.azure_conn:
                text("azure-storage-connection-string", cfg.azure_conn)

    chans = cfg.notify_channels or ""
    if any(h in chans for h in _WEBHOOK_HINTS) and cfg.notify_webhook_url:
        text("notify-webhook-url", cfg.notify_webhook_url)
    if "email" in chans:
        for cid, val in (("smtp-host", cfg.smtp_host), ("smtp-from", cfg.smtp_from),
                         ("smtp-to", cfg.smtp_to), ("smtp-user", cfg.smtp_user),
                         ("smtp-password", cfg.smtp_password)):
            text(cid, val)

    # Non-secret config -> Jenkins global env vars (the Jenkinsfile reads these).
    env_block: list[str] = []
    for key, val in (("SITE_JIRA", cfg.site_jira),
                     ("SITE_CONFLUENCE", cfg.site_confluence),
                     ("STORAGE_PROVIDER", cfg.storage_provider),
                     ("STORAGE_DEST", cfg.storage_dest),
                     ("S3_ENDPOINT_URL", cfg.s3_endpoint_url),
                     ("AWS_DEFAULT_REGION", cfg.aws_default_region),
                     ("NOTIFY_CHANNELS", cfg.notify_channels),
                     ("PRODUCT_NAME_TEMPLATE", cfg.product_name_template),
                     ("ARCHIVE_NAME_TEMPLATE", cfg.archive_name_template),
                     ("ARCHIVE_COMPRESSION", cfg.archive_compression),
                     ("BACKUP_CRON", cfg.backup_cron),
                     ("POLL_TIMEOUT", cfg.poll_timeout),
                     ("FAILURE_POLICY", cfg.failure_policy),
                     ("JIRA_COOLDOWN_ACTION", cfg.jira_cooldown_action),
                     ("PYTHON_BIN", cfg.python_bin)):
        if val:
            env_block.append(f'ev.put("{key}", b64d(\'{_b64(val)}\')); println("  env: {key}")')
            summary.append(f"global env {key} = {val}")

    # Per-outcome policy overrides — only emit the ones actually customized, so a
    # global env var exists only when the operator wants a persistent override
    # (otherwise the build parameter defaults to 'default' = follow the preset).
    for key, val in (("ON_COOLDOWN", cfg.on_cooldown),
                     ("ON_CREDENTIALS", cfg.on_credentials),
                     ("ON_BACKUP_ERROR", cfg.on_backup_error),
                     ("ON_NO_BACKUP", cfg.on_no_backup),
                     ("ON_UPLOAD_FAILURE", cfg.on_upload_failure)):
        if val and val != "default":
            env_block.append(f'ev.put("{key}", b64d(\'{_b64(val)}\')); println("  env: {key}")')
            summary.append(f"global env {key} = {val}")

    # Per-provider destination env vars — defaults for the Jenkins checkbox dest fields
    # (the Jenkinsfile reassembles STORAGE_DEST from these at build time).
    prov_list = [p.strip() for p in (cfg.storage_provider or "").split(",") if p.strip()]
    dest_list = [d.strip() for d in (cfg.storage_dest or "").split(",")]
    prov_dest_env = {"gcs": "GCS_BUCKET", "s3": "S3_BUCKET",
                     "azure": "AZURE_CONTAINER", "local": "LOCAL_PATH"}
    for i, prov in enumerate(prov_list):
        key = prov_dest_env.get(prov)
        val = dest_list[i] if i < len(dest_list) else ""
        if key and val:
            env_block.append(f'ev.put("{key}", b64d(\'{_b64(val)}\')); println("  env: {key}")')
            summary.append(f"global env {key} = {val}")

    groovy = (_TEMPLATE
              .replace("%%CRED_BLOCK%%", "\n".join(creds))
              .replace("%%ENV_BLOCK%%", "\n".join(env_block))
              .replace("%%JOB%%", job)
              .replace("%%REPO%%", repo)
              .replace("%%BRANCH%%", branch))
    summary.append(f"pipeline job: {job}  ->  {repo}  ({branch})")
    return groovy, summary


def write(cfg: config.Config, path: Path, **kwargs) -> tuple[Path, list[str]]:
    groovy, summary = build(cfg, **kwargs)
    path.write_text(groovy, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path, summary


_COOKIE_TEMPLATE = """\
// Update ONLY the jira-cookies credential. Paste into:
// Manage Jenkins -> Script Console -> Run. CONTAINS A SECRET — delete after running.
import com.cloudbees.plugins.credentials.CredentialsScope
import com.cloudbees.plugins.credentials.SystemCredentialsProvider
import com.cloudbees.plugins.credentials.domains.Domain
import org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl
import hudson.util.Secret

def store = SystemCredentialsProvider.getInstance().getStore()
def domain = Domain.global()
def b64d = { String s -> new String(s.decodeBase64(), "UTF-8") }
def cred = new StringCredentialsImpl(CredentialsScope.GLOBAL, "jira-cookies",
                                     "jira-cookies", Secret.fromString(b64d('%%BLOB%%')))
def existing = store.getCredentials(domain).find { it.id == "jira-cookies" }
if (existing != null) { store.updateCredentials(domain, existing, cred); println("Updated jira-cookies") }
else { store.addCredentials(domain, cred); println("Created jira-cookies") }
println("Done. Delete update-jira-cookies.groovy — it contains the cookie blob.")
"""


def build_cookie_update(cfg: config.Config) -> str:
    """Groovy that updates only the jira-cookies credential (for monthly refresh)."""
    return _COOKIE_TEMPLATE.replace("%%BLOB%%", _b64(cfg.jira_cookies))


def write_cookie_update(cfg: config.Config, path: Path) -> Path:
    path.write_text(build_cookie_update(cfg), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path
